export const semester = [1, 2, 3, 4, 5, 6, 7, 8];

export const collegeData = {
  name: 'School of Engineering',
  degree: ['B.Tech', 'M.Tech'],
  prgrm: [
    {
      name: '3D Printing and Design',
      initial: 'DP',
    },
    { name: 'Aeronautical Engineering', initial: 'AN' },
    { name: 'Aerospace Engineering', initial: 'AS' },
    { name: 'Artificial Intelligence & Data Science', initial: 'AD' },
    { name: 'Artificial Intelligence & Machine Learning', initial: 'AM' },
    { name: 'Automobile Engineering', initial: 'AE' },
    { name: 'Avionics Engineering', initial: 'AV' },
    { name: 'Big Data Analytics', initial: 'BD' },
    { name: 'Bioinformatics', initial: 'BF' },
    { name: 'Biomedical Engineering', initial: 'BE' },
    { name: 'Biotechnology', initial: 'BT' },
    { name: 'Blockchain', initial: 'BC' },
    // {
    //   name: 'Blockchain Technologies and Distributed Computing',
    //   initial: 'BT',
    // },
    { name: 'Cloud Technology', initial: 'CT' },
    { name: 'Cloud Technology and Information Security', initial: 'CI' },
    { name: 'Computer Science & Engineering', initial: 'CE' },
    { name: 'Consumer Technology', initial: 'CN' },
    { name: 'Cyber Forensics and Information Security', initial: 'CF' },
    { name: 'Cyber Security', initial: 'CS' },
    { name: 'Data Science', initial: 'DS' },
    { name: 'Digital Health and Innovation', initial: 'DH' },
    { name: 'Electric Vehicles', initial: 'EV' },
    { name: 'Food Technology', initial: 'FT' },
    { name: 'Full-stack Development', initial: 'FD' },
    { name: 'Game Development', initial: 'GD' },
    { name: 'Information Security', initial: 'IS' },
    { name: 'Internet of Things', initial: 'IN' },
    { name: 'Mechanical Engineering', initial: 'MH' },
    { name: 'Medical Biotechnology', initial: 'MB' },
    { name: 'Mobile Applications and Information Security', initial: 'MI' },
    { name: 'Robotics & Automation', initial: 'RO' },
    { name: 'Software Engineering', initial: 'SF' },
    { name: 'Space Technology', initial: 'ST' },
    { name: 'Web App Development', initial: 'WA' },
  ],
};
